# .github/workflows/print-text.yml
name: Print Text to File

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Text to write to file"
        required: true
        default: "Hello from GitHub Actions!"

jobs:
  write-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Data/print-to-file.js with input
        run: |
          export INPUT_TEXT="${{ github.event.inputs.text }}"
          node Data/print-to-file.js

      - name: Commit and push output
        run: |
          git config user.name "willywwh"
          git config user.email "william.streetracer.m5@gmail.com"
          git add Data/output.txt
          git commit -m "Append text to output file"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/willywwh/branchbob_onera.git HEAD:main
