# .github/workflows/print-text.yml
name: Print Text to File

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to write to file'
        required: true
        default: 'Hello from GitHub Actions!'

jobs:
  write-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run print-to-file.js with input
      run: |
        export INPUT_TEXT="${{ github.event.inputs.text }}"
        node print-to-file.js

    - name: Commit and push output
      run: |
        git config user.name "willywwh"
        git config user.email "william.streetracer.m5@gmail.com"
        git add Data/output.txt
        git commit -m "Update output.txt with new input"
        git push
